apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
    - port: 8080 #service port
      targetPort: 80 #container port
      nodePort: 30006  #any port between 30000 and 32767 [optional]